name: Update README ⭐
on:
  schedule:
    - cron: '10 5 1-25 12 *'

  workflow_dispatch:

  push:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 379535
          leaderboardId: 1179846
          sessionCookie: ${{ secrets.AOC_SESSION }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars
